### ISSUE TITLE
questions about authenticator and user's info

### ISSUE THREAD

**Issue by ghigt** [StephanDollberg/go-json-rest-middleware-jwt#3]
Hi,

With the basic example:

``` go
jwt_middleware := &jwt.JWTMiddleware{
    Key:        []byte("secret key"),
    Realm:      "jwt auth",
    Timeout:    time.Hour,
    MaxRefresh: time.Hour * 24,
    Authenticator: func(userId string, password string) bool {
        return userId == "admin" && password == "admin"
    },
}
rest.Route{"POST", "/login", jwt_middleware.LoginHandler}
```

I would like to know how to login wihtout a global variable (DB). Here, "admin" is written, but if I have to search in my DB, how can I do that if I only receive the `userId` and `password`?

Also, is it possible to add info of the user during the login? `isAdmin` or something else...

The only solution I found is to do not use `.LoginHandler`, but in this case `Authenticator` is also useless.

**Comment by StephanDollberg** [comment]
Hi @ghigt,

thanks for your questions.

1)
Yes, you can use some kind of wrapper to provide the function which has a db connection as a member variable:

``` go
type ApiWrapper struct {
    admin string
    // add all the variables you need - db, cache ....
}

func (a *ApiWrapper) auth(userId string, password string) bool {
    return userId == a.admin && password == "admin"
}
```

and then use it like

``` go
apiwrapper := ApiWrapper{"testuser"}
jwt_middleware := &jwt.JWTMiddleware{
    Authenticator: apiwrapper.auth,
    ...
}
```

I hope this satisfies your needs, though I think that a global isn't that bad in this case either.

2)
This is an interesting question. I assume you mean to set extra data in the jwt. I got a similar question some time ago. I have a [payload](https://github.com/StephanDollberg/go-json-rest-middleware-jwt/tree/payload) branch where the middleware supports an extra [payload callback](https://github.com/StephanDollberg/go-json-rest-middleware-jwt/blob/payload/auth_jwt.go#L48) that you can use to set values in the token. You can then receive them via `request.Env["JWT_PAYLOAD"]`.

If you are interested then you can try it and give me feedback. The reason why I haven't merged this yet is because I am not sure whether I want to have this functionality at all and whether this is a nice API.

Cheers,
Stephan

**Comment by ghigt** [comment]
Thank you :+1:

**Comment by ghigt** [comment]
It works fine with the payload. Could be interesting to merge it as I need to use the branch `payload` to use it. (I use it to keep the real `id` of my user to do not have to make a new request each time I need it).

**Comment by StephanDollberg** [comment]
Thanks for your feedback. I will think about it.

**Comment by boonep** [comment]
I would also request the payload branch to be merged.  It's very useful and shouldn't cause any issues.  Thanks!

**Comment by StephanDollberg** [comment]
I started to work on the tests today, will merge in the following days.

**Comment by StephanDollberg** [comment]
I merged the changes. Thanks again for the feedback!
